services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306


  wordpress:
    build:
      context: .
      dockerfile: ./docker/wordpress/Dockerfile
    container_name: wordpress
    restart: always
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    environment:
      DB_HOST: mysql
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend:/var/www/html:ro

    depends_on:
      - wordpress

volumes:
  mysql_data:
